//state_and_packet.pkt_0 = p.srcip

//state_and_packet.state_0 = heavy_hitter[p.srcip]
//state_and_packet.state_1 = hh_counter[p.srcip] 

|StateAndPacket| program (|StateAndPacket| state_and_packet) {
  state_and_packet.pkt_0 = state_and_packet.pkt_0;

  if () {
	state_and_packet.state_1 = state_and_packet.state_1 + 1;
	if (state_and_packet.state_1 = 1000) {
		state_and_packet.state_0 = 1;
	}
  }

  return state_and_packet;
}
